ARG BASE=fedora
ARG TAG
FROM ${BASE}:${TAG} AS sunshine-base

FROM sunshine-base as sunshine-build

ARG BRANCH
ARG BUILD_VERSION
ARG COMMIT
ARG TAG

ENV BRANCH=${BRANCH}
ENV BUILD_VERSION=${BUILD_VERSION}
ENV COMMIT=${COMMIT}
ENV TAG=${TAG}

# copy repository
RUN <<_REPO
#!/bin/bash
set -e
dnf -y install --setopt=install_weak_deps=False --best \
  git-core

mkdir -p /build
git clone -b v$BRANCH --recurse-submodules https://github.com/LizardByte/Sunshine.git /build/sunshine
_REPO

WORKDIR /build/sunshine/

RUN <<_BUILD
#!/bin/bash
set -e
echo '#!/bin/sh' > src_assets/linux/misc/postinst

chmod +x ./scripts/linux_build.sh
./scripts/linux_build.sh --sudo-off --skip-cuda
dnf clean all
rm -rf /var/cache/yum

mkdir -p /rpmbuild/$(arch)
mv /build/sunshine/build/cpack_artifacts/Sunshine.rpm /rpmbuild/$(arch)/sunshine-$BRANCH.fc$TAG.$(arch).rpm
_BUILD

FROM alpine:latest AS artifacts
COPY --from=sunshine-build /rpmbuild/ /rpmbuild/