apiVersion: v1
entries:
  authelia:
  - apiVersion: v2
    appVersion: 4.37.5
    created: "2023-12-14T03:33:41.502542887Z"
    description: Authelia is a Single Sign-On Multi-Factor portal for web apps
    digest: c7fbd921842eaa3738aa7f567d4dce5989bd4426b02c165cf4990a4fb771121d
    home: https://www.authelia.com
    icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
    keywords:
    - SSO
    - Authentication
    - Security
    - Two-Factor
    - YubiKey
    - Webauthn
    - Duo
    - TOTP
    - Time-based One Time Password
    - Push Notifications
    - LDAP
    kubeVersion: '>= 1.13.0-0'
    maintainers:
    - email: james-d-elliott@users.noreply.github.com
      name: james-d-elliott
      url: https://github.com/james-d-elliott
    name: authelia
    sources:
    - https://github.com/authelia/chartrepo/tree/master/charts/authelia
    - https://www.github.com/authelia/authelia
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/authelia-0.8.58.tgz
    version: 0.8.58
  cluster-services:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.502695135Z"
    description: Basic cluster services with minimal configuration
    digest: dc7542e3b4eb03184c8be77e14334dbaab2ea5ff5b71d408984b520936195854
    name: cluster-services
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/cluster-services-0.2.5.tgz
    version: 0.2.5
  code:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.50309446Z"
    digest: 6707d3b1a2d5edfe92485565c3293bfc0a195c6720e0c6469e310449bfc4cb27
    name: code
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/code-0.1.21.tgz
    version: 0.1.21
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.502958373Z"
    digest: 0f33783ed6caacb2b9209a5a33cda657c379f3a3b6de06e5fe64103fb23bf987
    name: code
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/code-0.1.19.tgz
    version: 0.1.19
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.502821233Z"
    digest: aabe3fc1a0e3fc35abec77750dbbe9fe6da867c28372f172eb1c17a25913700c
    name: code
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/code-0.1.17.tgz
    version: 0.1.17
  external-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503254142Z"
    description: external-dns
    digest: ff9fc8a348069b7dd31acedf6f6249d19931a3666e1ca0e5ec7de4ad89278181
    name: external-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/external-dns-0.1.15.tgz
    version: 0.1.15
  headscale:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503391541Z"
    description: A Helm chart for Kubernetes
    digest: 18e01c034999a5cea1d18635d2becb92475b0448a599d7a971728d9a4688b5e1
    name: headscale
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/headscale-0.1.4.tgz
    version: 0.1.4
  helm-wrapper:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503448469Z"
    description: Wrap any manifest in helm to use terraform helm provider
    digest: c1305f3c2535b5569c210cbf28f1bd566b6f37777a6c413fcdbe3b30f959240a
    name: helm-wrapper
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/helm-wrapper-0.1.0.tgz
    version: 0.1.0
  hostapd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503529552Z"
    description: A Helm chart for Kubernetes
    digest: 18ef6358a9b3afeaf10f5b046a98cf221125f6a451d272f2c74a0e8c5991dd47
    name: hostapd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/hostapd-0.1.8.tgz
    version: 0.1.8
  kasm-desktop:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504325076Z"
    description: Basic cluster services with minimal configuration
    digest: b3b167f3041e57f586c7460c180d5456ae5a0daf09f9a1e31ce4df8187dcd62d
    name: kasm-desktop
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kasm-desktop-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504148412Z"
    description: Basic cluster services with minimal configuration
    digest: 793a49f5329cf412276d2e0d167472b3a4b4dad696a3b0dc29cd7149edd43e9b
    name: kasm-desktop
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kasm-desktop-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503977509Z"
    description: Basic cluster services with minimal configuration
    digest: 730af3e658e2cce2b77296b9a2237d95f13b77a1bdeef8020e4d2b474b48f177
    name: kasm-desktop
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kasm-desktop-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.503805925Z"
    description: Basic cluster services with minimal configuration
    digest: e064c37a093e43baf7b77f41186d5001edf211d303eb30feda990b525ff872ed
    name: kasm-desktop
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kasm-desktop-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.5036713Z"
    description: Basic cluster services with minimal configuration
    digest: ca722a1ae13a595cd60a2c4c88e85c02fbe5413a0aac209e1a1b5e31b2ee418d
    name: kasm-desktop
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kasm-desktop-0.1.7.tgz
    version: 0.1.7
  kea:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504432619Z"
    description: Kea
    digest: 51fac6adec8b455ff7c6887bf3e0ffd0eb0866788c5d693e62c960ca6022ec1b
    name: kea
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kea-0.1.18.tgz
    version: 0.1.18
  kube-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504588554Z"
    description: kube-dns
    digest: 4df12e37b29b24bd2da08e25803bea114304e48c87ec3be4162fd2c7b02dfce6
    name: kube-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kube-dns-0.1.0.tgz
    version: 0.1.0
  matchbox:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504763575Z"
    description: Matchbox PXE boot
    digest: cba665ac04f08302d675ec4ea99865bbffb75c6ef5b6a96e3ce90ee77d9af306
    name: matchbox
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/matchbox-0.2.14.tgz
    version: 0.2.14
  mpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.504965056Z"
    description: A Helm chart for Kubernetes
    digest: f3e9bf4a6cf1ef2618cdd6209e34028f6dd8fc6edfcf2d523d1f61b38bb3b69b
    name: mpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/mpd-0.4.6.tgz
    version: 0.4.6
  simulation:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.505403124Z"
    description: A Helm chart for Kubernetes
    digest: 697f33f2b4a1bb9f8ab86880556f686fde0d60a428ae441de3381b14e9e4f373
    name: simulation
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/simulation-0.1.8.tgz
    version: 0.1.8
  stream-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.505554079Z"
    description: A Helm chart for Kubernetes
    digest: 2ce6a0516623427dc18b7dba8b2fda0b43382cb4b2975614ffc65f3cd19d7dad
    name: stream-server
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/stream-server-0.1.7.tgz
    version: 0.1.7
  tailscale:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.505700195Z"
    description: A Helm chart for Kubernetes
    digest: dc9c16939223e9385c13fe6fdc07e6c8820c955dc93063d678d3119d2c561e77
    name: tailscale
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/tailscale-0.1.9.tgz
    version: 0.1.9
  tftpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.505810504Z"
    description: TFTPD
    digest: 55773b597e9aad0ad95426dc40a780d0786479311f1f0b4f39aed82bea88a0c6
    name: tftpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/tftpd-0.1.1.tgz
    version: 0.1.1
  transmission:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.505980896Z"
    description: A Helm chart for Kubernetes
    digest: 3dc8a7d65e6f7c6a205046b6bcce2b0ef257f9d4ba48f634ccaba6a30870fbfc
    name: transmission
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/transmission-0.1.7.tgz
    version: 0.1.7
  vaultwarden:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.506155596Z"
    description: A Helm chart for Kubernetes
    digest: af8917dc4d9430a5ed1c17700fbcc091777cb6982b4830842c276eba55bd4356
    name: vaultwarden
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/vaultwarden-0.1.12.tgz
    version: 0.1.12
  webdav:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T03:33:41.506303285Z"
    description: A Helm chart for Kubernetes
    digest: 2eb8cb9f1cd32f9051ce0387fa780c17ac28e810846a6a8ec08f5ccbff24fdd9
    name: webdav
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/webdav-0.1.5.tgz
    version: 0.1.5
generated: "2023-12-14T03:33:41.500370822Z"
