apiVersion: v1
entries:
  cluster-services:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.68916757-07:00"
    description: Basic cluster services with minimal configuration
    digest: 622b2294390ec8ef51480be3eaec5ac7f2c50aa099ffaa1ab28b83365a27254b
    name: cluster-services
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/cluster-services-0.2.4.tgz
    version: 0.2.4
  external-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.689934538-07:00"
    description: external-dns
    digest: ff9fc8a348069b7dd31acedf6f6249d19931a3666e1ca0e5ec7de4ad89278181
    name: external-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/external-dns-0.1.15.tgz
    version: 0.1.15
  helm-wrapper:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.690131197-07:00"
    description: Wrap any manifest in helm to use terraform helm provider
    digest: c1305f3c2535b5569c210cbf28f1bd566b6f37777a6c413fcdbe3b30f959240a
    name: helm-wrapper
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/helm-wrapper-0.1.0.tgz
    version: 0.1.0
  hostapd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.690343125-07:00"
    description: A Helm chart for Kubernetes
    digest: 18ef6358a9b3afeaf10f5b046a98cf221125f6a451d272f2c74a0e8c5991dd47
    name: hostapd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/hostapd-0.1.8.tgz
    version: 0.1.8
  kea:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.690585011-07:00"
    description: Kea
    digest: e4221c6b11064dd30e511b9ccf6b9f8aaa36615227d3f5fbff7781249b70da25
    name: kea
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kea-0.1.15.tgz
    version: 0.1.15
  kube-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.690881493-07:00"
    description: kube-dns
    digest: 4df12e37b29b24bd2da08e25803bea114304e48c87ec3be4162fd2c7b02dfce6
    name: kube-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kube-dns-0.1.0.tgz
    version: 0.1.0
  matchbox:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.691174037-07:00"
    description: Matchbox PXE boot
    digest: cba665ac04f08302d675ec4ea99865bbffb75c6ef5b6a96e3ce90ee77d9af306
    name: matchbox
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/matchbox-0.2.14.tgz
    version: 0.2.14
  mpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.691493222-07:00"
    description: A Helm chart for Kubernetes
    digest: f3e9bf4a6cf1ef2618cdd6209e34028f6dd8fc6edfcf2d523d1f61b38bb3b69b
    name: mpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/mpd-0.4.6.tgz
    version: 0.4.6
  simulation:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.691820422-07:00"
    description: A Helm chart for Kubernetes
    digest: 907ddcd20365b8f0c6d2a1704ae48911c846e823a6ff09650e11ab5f07e5dbbf
    name: simulation
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/simulation-0.1.3.tgz
    version: 0.1.3
  stream-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.692252625-07:00"
    description: A Helm chart for Kubernetes
    digest: e052824106a65d8ba97e0ff533ec2c0937fc5c91dfd00107c322de7e17e7cde6
    name: stream-server
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/stream-server-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.692129358-07:00"
    description: A Helm chart for Kubernetes
    digest: eafb358a550b5737d674926ed01893e0395be08aeb17c7be1a6ec676c4778866
    name: stream-server
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/stream-server-0.1.5.tgz
    version: 0.1.5
  tftpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.692457691-07:00"
    description: TFTPD
    digest: 55773b597e9aad0ad95426dc40a780d0786479311f1f0b4f39aed82bea88a0c6
    name: tftpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/tftpd-0.1.1.tgz
    version: 0.1.1
  transmission:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.692745836-07:00"
    description: A Helm chart for Kubernetes
    digest: 3dc8a7d65e6f7c6a205046b6bcce2b0ef257f9d4ba48f634ccaba6a30870fbfc
    name: transmission
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/transmission-0.1.7.tgz
    version: 0.1.7
  webdav:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-01T14:57:53.693018351-07:00"
    description: A Helm chart for Kubernetes
    digest: 2eb8cb9f1cd32f9051ce0387fa780c17ac28e810846a6a8ec08f5ccbff24fdd9
    name: webdav
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/webdav-0.1.5.tgz
    version: 0.1.5
generated: "2023-05-01T14:57:53.680273679-07:00"
