apiVersion: v1
entries:
  authelia:
  - apiVersion: v2
    appVersion: 4.37.5
    created: "2023-07-20T00:12:26.399591978-07:00"
    description: Authelia is a Single Sign-On Multi-Factor portal for web apps
    digest: 146a421f49915acc20de2b005892b10f4c7bbdc9cc9a33de9dff0a0e2c9860d3
    home: https://www.authelia.com
    icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
    keywords:
    - SSO
    - Authentication
    - Security
    - Two-Factor
    - YubiKey
    - Webauthn
    - Duo
    - TOTP
    - Time-based One Time Password
    - Push Notifications
    - LDAP
    kubeVersion: '>= 1.13.0-0'
    maintainers:
    - email: james-d-elliott@users.noreply.github.com
      name: james-d-elliott
      url: https://github.com/james-d-elliott
    name: authelia
    sources:
    - https://github.com/authelia/chartrepo/tree/master/charts/authelia
    - https://www.github.com/authelia/authelia
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/authelia-0.8.57.tgz
    version: 0.8.57
  cluster-services:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.399764108-07:00"
    description: Basic cluster services with minimal configuration
    digest: dc7542e3b4eb03184c8be77e14334dbaab2ea5ff5b71d408984b520936195854
    name: cluster-services
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/cluster-services-0.2.5.tgz
    version: 0.2.5
  dev:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.399915668-07:00"
    digest: 3239222cd0d731a784d388395f3598ce89b345a96d76c8ad2c05d0ee17ecda48
    name: dev
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/dev-0.1.5.tgz
    version: 0.1.5
  external-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400113497-07:00"
    description: external-dns
    digest: ff9fc8a348069b7dd31acedf6f6249d19931a3666e1ca0e5ec7de4ad89278181
    name: external-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/external-dns-0.1.15.tgz
    version: 0.1.15
  helm-wrapper:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400180615-07:00"
    description: Wrap any manifest in helm to use terraform helm provider
    digest: c1305f3c2535b5569c210cbf28f1bd566b6f37777a6c413fcdbe3b30f959240a
    name: helm-wrapper
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/helm-wrapper-0.1.0.tgz
    version: 0.1.0
  hostapd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400273854-07:00"
    description: A Helm chart for Kubernetes
    digest: 18ef6358a9b3afeaf10f5b046a98cf221125f6a451d272f2c74a0e8c5991dd47
    name: hostapd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/hostapd-0.1.8.tgz
    version: 0.1.8
  kea:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.40038125-07:00"
    description: Kea
    digest: e4221c6b11064dd30e511b9ccf6b9f8aaa36615227d3f5fbff7781249b70da25
    name: kea
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kea-0.1.15.tgz
    version: 0.1.15
  kube-dns:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400559371-07:00"
    description: kube-dns
    digest: 4df12e37b29b24bd2da08e25803bea114304e48c87ec3be4162fd2c7b02dfce6
    name: kube-dns
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/kube-dns-0.1.0.tgz
    version: 0.1.0
  matchbox:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400744836-07:00"
    description: Matchbox PXE boot
    digest: cba665ac04f08302d675ec4ea99865bbffb75c6ef5b6a96e3ce90ee77d9af306
    name: matchbox
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/matchbox-0.2.14.tgz
    version: 0.2.14
  mpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.400949568-07:00"
    description: A Helm chart for Kubernetes
    digest: f3e9bf4a6cf1ef2618cdd6209e34028f6dd8fc6edfcf2d523d1f61b38bb3b69b
    name: mpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/mpd-0.4.6.tgz
    version: 0.4.6
  simulation:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.401140123-07:00"
    description: A Helm chart for Kubernetes
    digest: 697f33f2b4a1bb9f8ab86880556f686fde0d60a428ae441de3381b14e9e4f373
    name: simulation
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/simulation-0.1.8.tgz
    version: 0.1.8
  stream-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.40132182-07:00"
    description: A Helm chart for Kubernetes
    digest: 2ce6a0516623427dc18b7dba8b2fda0b43382cb4b2975614ffc65f3cd19d7dad
    name: stream-server
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/stream-server-0.1.7.tgz
    version: 0.1.7
  tailscale:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.401506754-07:00"
    description: A Helm chart for Kubernetes
    digest: aa946cefdb887655e570c92c3ab58451fb3eb580e5be0d09ea448f14119d4628
    name: tailscale
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/tailscale-0.1.6.tgz
    version: 0.1.6
  tftpd:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.401624861-07:00"
    description: TFTPD
    digest: 55773b597e9aad0ad95426dc40a780d0786479311f1f0b4f39aed82bea88a0c6
    name: tftpd
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/tftpd-0.1.1.tgz
    version: 0.1.1
  transmission:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.402077868-07:00"
    description: A Helm chart for Kubernetes
    digest: 3dc8a7d65e6f7c6a205046b6bcce2b0ef257f9d4ba48f634ccaba6a30870fbfc
    name: transmission
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/transmission-0.1.7.tgz
    version: 0.1.7
  vaultwarden:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.402456272-07:00"
    description: A Helm chart for Kubernetes
    digest: b793144d97805023f99da8fe18bd97fda273243e9f2a335dc8f0b1d3bda08a61
    name: vaultwarden
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/vaultwarden-0.1.11.tgz
    version: 0.1.11
  webdav:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-20T00:12:26.402720138-07:00"
    description: A Helm chart for Kubernetes
    digest: 2eb8cb9f1cd32f9051ce0387fa780c17ac28e810846a6a8ec08f5ccbff24fdd9
    name: webdav
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/webdav-0.1.5.tgz
    version: 0.1.5
generated: "2023-07-20T00:12:26.397055381-07:00"
