apiVersion: v1
entries:
  helm-wrapper:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-01-21T01:35:55.313701819-08:00"
    description: Wrap any manifest in helm to use terraform helm provider
    digest: c1305f3c2535b5569c210cbf28f1bd566b6f37777a6c413fcdbe3b30f959240a
    name: helm-wrapper
    type: application
    urls:
    - https://randomcoww.github.io/repos/helm/helm-wrapper-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-21T01:35:55.313462626-08:00"
